<a href="https://colab.research.google.com/github/Ric-Royal/Moringa-IP/blob/master/Moringa_School_DS_WK_9_IP_Richard_Kabiru.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Defining the Question

### a) Specifying the Question

 
1.   Do the different independent variables determine if someone survived? 
2.  Do the the different factors assist in categorising the email as spam? 

### b) Defining the Metric for Success

Model should have a minimum of 80% accuracy
The model precision for the train dataset should be

1.   Survived > 0.70
2.   not survive > 0.70

The model precision for the spam dataset should be


1.   spam > 0.85
2.   Not spam > 0.70



### c) Understanding the context 

The train dataset is from a passenger ship that had an accident. The different categories indicate the passenger class, their ticket number, cabin where they spent their time during the voyage and the names of the passengers. 

The other dataset contain details on information contained in the emails. It categorizes the emails into spam or not spamby using the number of letters, words, punctuation marks e.t.c.

### d) Recording the Experimental Design

CRISP-DM methodology was used.

## 2. Reading the Data

In [180]:
# Importing libraries
#
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
from sklearn.model_selection import train_test_split

In [181]:
# Loading the Dataset
#
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
columns = ['word_freq_make:', 'word_freq_address:', 'word_freq_all:', 'word_freq_3d:', 'word_freq_our:', 'word_freq_over:', 'word_freq_remove:', 'word_freq_internet:', 'word_freq_order:', 'word_freq_mail:', 'word_freq_receive:', 'word_freq_will:', 'word_freq_people:', 'word_freq_report:', 'word_freq_addresses:', 'word_freq_free:', 'word_freq_business:', 'word_freq_email:', 'word_freq_you:', 'word_freq_credit:', 'word_freq_your:', 'word_freq_font:', 'word_freq_000:' , 'word_freq_money:', 'word_freq_hp:', 'word_freq_hpl:', 'word_freq_george:', 'word_freq_650:', 'word_freq_lab:', 'word_freq_labs:', 'word_freq_telnet:', 'word_freq_857:', 'word_freq_data:', 'word_freq_415:', 'word_freq_85:', 'word_freq_technology:', 'word_freq_1999:', 'word_freq_parts:', 'word_freq_pm:', 'word_freq_direct:', 'word_freq_cs:', 'word_freq_meeting:', 'word_freq_original:', 'word_freq_project:', 'word_freq_re:', 'word_freq_edu:', 'word_freq_table:', 'word_freq_conference:', 'char_freq_;:', 'char_freq_(:', 'char_freq_[:', 'char_freq_!:', 'char_freq_$:', 'char_freq_#:', 'capital_run_length_average:', 'capital_run_length_longest:', 'capital_run_length_total:', 'spam']
spam = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/spambase/spambase.data', names= columns, index_col= False)

In [182]:
import zipfile
archive = zipfile.ZipFile('spambase.zip', 'r')
df = archive.read('spambase.names')

In [183]:
df

b'| SPAM E-MAIL DATABASE ATTRIBUTES (in .names format)\r\n|\r\n| 48 continuous real [0,100] attributes of type word_freq_WORD \r\n| = percentage of words in the e-mail that match WORD,\r\n| i.e. 100 * (number of times the WORD appears in the e-mail) / \r\n| total number of words in e-mail.  A "word" in this case is any \r\n| string of alphanumeric characters bounded by non-alphanumeric \r\n| characters or end-of-string.\r\n|\r\n| 6 continuous real [0,100] attributes of type char_freq_CHAR\r\n| = percentage of characters in the e-mail that match CHAR,\r\n| i.e. 100 * (number of CHAR occurences) / total characters in e-mail\r\n|\r\n| 1 continuous real [1,...] attribute of type capital_run_length_average\r\n| = average length of uninterrupted sequences of capital letters\r\n|\r\n| 1 continuous integer [1,...] attribute of type capital_run_length_longest\r\n| = length of longest uninterrupted sequence of capital letters\r\n|\r\n| 1 continuous integer [1,...] attribute of type capital_run_l

In [184]:
spam.head()

word_freq_make:  word_freq_address:  ...  capital_run_length_total:  spam
0             0.00                0.64  ...                        278     1
1             0.21                0.28  ...                       1028     1
2             0.06                0.00  ...                       2259     1
3             0.00                0.00  ...                        191     1
4             0.00                0.00  ...                        191     1

[5 rows x 58 columns]

## 3. Checking the Data

In [185]:
# Determining the no. of records in the dataset
#
train.shape

(891, 12)

In [186]:
# Determining the no. of records in the dataset
#
test.shape

(418, 11)

In [187]:
# Determining the no. of records in the dataset
#
spam.shape

(4601, 58)

In [188]:
# Previewing the top of the dataset
#
train.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [189]:
# Previewing the top of the dataset
#
test.head()

PassengerId  Pclass  ... Cabin Embarked
0          892       3  ...   NaN        Q
1          893       3  ...   NaN        S
2          894       2  ...   NaN        Q
3          895       3  ...   NaN        S
4          896       3  ...   NaN        S

[5 rows x 11 columns]

In [190]:
# Previewing the top of the dataset
#
spam.head()

word_freq_make:  word_freq_address:  ...  capital_run_length_total:  spam
0             0.00                0.64  ...                        278     1
1             0.21                0.28  ...                       1028     1
2             0.06                0.00  ...                       2259     1
3             0.00                0.00  ...                        191     1
4             0.00                0.00  ...                        191     1

[5 rows x 58 columns]

In [191]:
# Previewing the bottom of the dataset
# 
train.tail()

PassengerId  Survived  Pclass  ...   Fare Cabin  Embarked
886          887         0       2  ...  13.00   NaN         S
887          888         1       1  ...  30.00   B42         S
888          889         0       3  ...  23.45   NaN         S
889          890         1       1  ...  30.00  C148         C
890          891         0       3  ...   7.75   NaN         Q

[5 rows x 12 columns]

In [192]:
# Previewing the bottom of the dataset
# 
test.tail()

PassengerId  Pclass                          Name  ...      Fare  Cabin  Embarked
413         1305       3            Spector, Mr. Woolf  ...    8.0500    NaN         S
414         1306       1  Oliva y Ocana, Dona. Fermina  ...  108.9000   C105         C
415         1307       3  Saether, Mr. Simon Sivertsen  ...    7.2500    NaN         S
416         1308       3           Ware, Mr. Frederick  ...    8.0500    NaN         S
417         1309       3      Peter, Master. Michael J  ...   22.3583    NaN         C

[5 rows x 11 columns]

In [193]:
# Previewing the bottom of the dataset
# 
spam.tail()

word_freq_make:  word_freq_address:  ...  capital_run_length_total:  spam
4596             0.31                 0.0  ...                         88     0
4597             0.00                 0.0  ...                         14     0
4598             0.30                 0.0  ...                        118     0
4599             0.96                 0.0  ...                         78     0
4600             0.00                 0.0  ...                         40     0

[5 rows x 58 columns]

In [194]:
# Checking whether each column in the dataset has an appropriate datatype
#
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [195]:
# Checking whether each column in the dataset has an appropriate datatype
#
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB


In [196]:
# Checking whether each column in the dataset has an appropriate datatype
#
spam.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4601 entries, 0 to 4600
Data columns (total 58 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   word_freq_make:              4601 non-null   float64
 1   word_freq_address:           4601 non-null   float64
 2   word_freq_all:               4601 non-null   float64
 3   word_freq_3d:                4601 non-null   float64
 4   word_freq_our:               4601 non-null   float64
 5   word_freq_over:              4601 non-null   float64
 6   word_freq_remove:            4601 non-null   float64
 7   word_freq_internet:          4601 non-null   float64
 8   word_freq_order:             4601 non-null   float64
 9   word_freq_mail:              4601 non-null   float64
 10  word_freq_receive:           4601 non-null   float64
 11  word_freq_will:              4601 non-null   float64
 12  word_freq_people:            4601 non-null   float64
 13  word_freq_report: 

In [197]:
# Checking for unique values
train.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [198]:
# Checking for unique values
test.nunique()

PassengerId    418
Pclass           3
Name           418
Sex              2
Age             79
SibSp            7
Parch            8
Ticket         363
Fare           169
Cabin           76
Embarked         3
dtype: int64

In [199]:
# Checking for unique values
spam.nunique()

word_freq_make:                 142
word_freq_address:              171
word_freq_all:                  214
word_freq_3d:                    43
word_freq_our:                  255
word_freq_over:                 141
word_freq_remove:               173
word_freq_internet:             170
word_freq_order:                144
word_freq_mail:                 245
word_freq_receive:              113
word_freq_will:                 316
word_freq_people:               158
word_freq_report:               133
word_freq_addresses:            118
word_freq_free:                 253
word_freq_business:             197
word_freq_email:                229
word_freq_you:                  575
word_freq_credit:               148
word_freq_your:                 401
word_freq_font:                  99
word_freq_000:                  164
word_freq_money:                143
word_freq_hp:                   395
word_freq_hpl:                  281
word_freq_george:               240
word_freq_650:              

In [200]:
# Checking for null values.
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [201]:
# Checking for null values.
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [202]:
# Checking for null values.
spam.isnull().sum()

word_freq_make:                0
word_freq_address:             0
word_freq_all:                 0
word_freq_3d:                  0
word_freq_our:                 0
word_freq_over:                0
word_freq_remove:              0
word_freq_internet:            0
word_freq_order:               0
word_freq_mail:                0
word_freq_receive:             0
word_freq_will:                0
word_freq_people:              0
word_freq_report:              0
word_freq_addresses:           0
word_freq_free:                0
word_freq_business:            0
word_freq_email:               0
word_freq_you:                 0
word_freq_credit:              0
word_freq_your:                0
word_freq_font:                0
word_freq_000:                 0
word_freq_money:               0
word_freq_hp:                  0
word_freq_hpl:                 0
word_freq_george:              0
word_freq_650:                 0
word_freq_lab:                 0
word_freq_labs:                0
word_freq_

## Tidying the Dataset

In [203]:
# Replacing null values
train['Age'].fillna(train['Age'].median(), inplace= True)

In [204]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [205]:
# Dropping the cabin column.
train = train.drop(columns= 'Cabin', axis= 1)

In [206]:
train = train.dropna()

In [207]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  889 non-null    int64  
 1   Survived     889 non-null    int64  
 2   Pclass       889 non-null    int64  
 3   Name         889 non-null    object 
 4   Sex          889 non-null    object 
 5   Age          889 non-null    float64
 6   SibSp        889 non-null    int64  
 7   Parch        889 non-null    int64  
 8   Ticket       889 non-null    object 
 9   Fare         889 non-null    float64
 10  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(4)
memory usage: 83.3+ KB


In [208]:
# Replacing null values
test['Age'].fillna(test['Age'].median(), inplace= True)

In [209]:
# Dropping the cabin column.
test = test.drop(columns= 'Cabin', axis= 1)

In [210]:
# Replacing null values
test['Fare'].fillna(test['Fare'].mean(), inplace= True)

In [211]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          418 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         418 non-null    float64
 9   Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(4)
memory usage: 32.8+ KB


In [212]:
from sklearn.preprocessing import LabelEncoder
# creating instance of labelencoder
labelencoder = LabelEncoder()

train['Sex_Cat'] = labelencoder.fit_transform(train['Sex'])
train['Embarked_Cat'] = labelencoder.fit_transform(train['Embarked'])
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   PassengerId   889 non-null    int64  
 1   Survived      889 non-null    int64  
 2   Pclass        889 non-null    int64  
 3   Name          889 non-null    object 
 4   Sex           889 non-null    object 
 5   Age           889 non-null    float64
 6   SibSp         889 non-null    int64  
 7   Parch         889 non-null    int64  
 8   Ticket        889 non-null    object 
 9   Fare          889 non-null    float64
 10  Embarked      889 non-null    object 
 11  Sex_Cat       889 non-null    int64  
 12  Embarked_Cat  889 non-null    int64  
dtypes: float64(2), int64(7), object(4)
memory usage: 97.2+ KB


In [213]:
# Getting the IQR Score
Q1 = spam.iloc[:, 0:56].quantile(0.25)
Q3 = spam.iloc[:, 0:56].quantile(0.75)
IQR = Q3 - Q1
IQR

word_freq_make:                 0.000
word_freq_address:              0.000
word_freq_all:                  0.420
word_freq_3d:                   0.000
word_freq_our:                  0.380
word_freq_over:                 0.000
word_freq_remove:               0.000
word_freq_internet:             0.000
word_freq_order:                0.000
word_freq_mail:                 0.160
word_freq_receive:              0.000
word_freq_will:                 0.800
word_freq_people:               0.000
word_freq_report:               0.000
word_freq_addresses:            0.000
word_freq_free:                 0.100
word_freq_business:             0.000
word_freq_email:                0.000
word_freq_you:                  2.640
word_freq_credit:               0.000
word_freq_your:                 1.270
word_freq_font:                 0.000
word_freq_000:                  0.000
word_freq_money:                0.000
word_freq_hp:                   0.000
word_freq_hpl:                  0.000
word_freq_ge

## 4. K - Nearest Neighbor (K-NN)

In [48]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   PassengerId   889 non-null    int64  
 1   Survived      889 non-null    int64  
 2   Pclass        889 non-null    int64  
 3   Name          889 non-null    object 
 4   Sex           889 non-null    object 
 5   Age           889 non-null    float64
 6   SibSp         889 non-null    int64  
 7   Parch         889 non-null    int64  
 8   Ticket        889 non-null    object 
 9   Fare          889 non-null    float64
 10  Embarked      889 non-null    object 
 11  Sex_Cat       889 non-null    int64  
 12  Embarked_Cat  889 non-null    int64  
dtypes: float64(2), int64(7), object(4)
memory usage: 97.2+ KB


In [145]:
# Splitting the independent and dependent variables

X = train[['Pclass', 'Sex_Cat', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked_Cat']]
y = train.iloc[:, 1].values

In [146]:
# Importing train_test_split
from sklearn.model_selection import train_test_split

# Training using 80% of the data.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state= 0, test_size= 0.2)


In [147]:
# Feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [150]:
# Training and predictions
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 4)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=4, p=2,
                     weights='uniform')

In [151]:
# Making prediction on the resting data

y_pred = classifier.predict(X_test)

In [152]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[90 15]
 [35 38]]
              precision    recall  f1-score   support

           0       0.72      0.86      0.78       105
           1       0.72      0.52      0.60        73

    accuracy                           0.72       178
   macro avg       0.72      0.69      0.69       178
weighted avg       0.72      0.72      0.71       178



In [153]:
# Importing train_test_split
from sklearn.model_selection import train_test_split

# Training using 70% of the data.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state= 0, test_size= 0.3)


In [154]:
# Feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [155]:
# Training and predictions
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 4)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=4, p=2,
                     weights='uniform')

In [156]:
# Making prediction on the resting data

y_pred = classifier.predict(X_test)

In [157]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[140  17]
 [ 43  67]]
              precision    recall  f1-score   support

           0       0.77      0.89      0.82       157
           1       0.80      0.61      0.69       110

    accuracy                           0.78       267
   macro avg       0.78      0.75      0.76       267
weighted avg       0.78      0.78      0.77       267



In [159]:
# Importing train_test_split
from sklearn.model_selection import train_test_split

# Training using 60% of the data.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state= 0, test_size= 0.4)

In [160]:
# Feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [161]:
# Training and predictions
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 4)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=4, p=2,
                     weights='uniform')

In [162]:
# Making prediction on the resting data

y_pred = classifier.predict(X_test)

In [163]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[187  29]
 [ 54  86]]
              precision    recall  f1-score   support

           0       0.78      0.87      0.82       216
           1       0.75      0.61      0.67       140

    accuracy                           0.77       356
   macro avg       0.76      0.74      0.75       356
weighted avg       0.76      0.77      0.76       356



### LDA with KNN

In [164]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   PassengerId   889 non-null    int64  
 1   Survived      889 non-null    int64  
 2   Pclass        889 non-null    int64  
 3   Name          889 non-null    object 
 4   Sex           889 non-null    object 
 5   Age           889 non-null    float64
 6   SibSp         889 non-null    int64  
 7   Parch         889 non-null    int64  
 8   Ticket        889 non-null    object 
 9   Fare          889 non-null    float64
 10  Embarked      889 non-null    object 
 11  Sex_Cat       889 non-null    int64  
 12  Embarked_Cat  889 non-null    int64  
dtypes: float64(2), int64(7), object(4)
memory usage: 97.2+ KB


In [165]:
# Splitting the independent and dependent variables

X = train[['Pclass', 'Sex_Cat', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked_Cat']]
y = train.iloc[:, 1].values

In [166]:
# Peforming LDA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components= 5)
X_train = lda.fit_transform(X_train, y_train)
X_test = lda.transform(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/discriminant_analysis.py:463: ChangedBehaviorWarning: n_components cannot be larger than min(n_features, n_classes - 1). Using min(n_features, n_classes - 1) = min(7, 2 - 1) = 1 components.
  ChangedBehaviorWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/discriminant_analysis.py:469: FutureWarning: In version 0.23, setting n_components > min(n_features, n_classes - 1) will raise a ValueError. You should set n_components to None (default), or a value smaller or equal to min(n_features, n_classes - 1).
  warnings.warn(future_msg, FutureWarning)


In [167]:
# Training and predictions
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5)
classifier.fit(X_train, y_train)

# Making prediction on the resting data

y_pred = classifier.predict(X_test)

In [168]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[179  37]
 [ 59  81]]
              precision    recall  f1-score   support

           0       0.75      0.83      0.79       216
           1       0.69      0.58      0.63       140

    accuracy                           0.73       356
   macro avg       0.72      0.70      0.71       356
weighted avg       0.73      0.73      0.73       356



## 5. Naive Bayes Classifier

In [214]:
spam.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4601 entries, 0 to 4600
Data columns (total 58 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   word_freq_make:              4601 non-null   float64
 1   word_freq_address:           4601 non-null   float64
 2   word_freq_all:               4601 non-null   float64
 3   word_freq_3d:                4601 non-null   float64
 4   word_freq_our:               4601 non-null   float64
 5   word_freq_over:              4601 non-null   float64
 6   word_freq_remove:            4601 non-null   float64
 7   word_freq_internet:          4601 non-null   float64
 8   word_freq_order:             4601 non-null   float64
 9   word_freq_mail:              4601 non-null   float64
 10  word_freq_receive:           4601 non-null   float64
 11  word_freq_will:              4601 non-null   float64
 12  word_freq_people:            4601 non-null   float64
 13  word_freq_report: 

In [215]:
# Implementing the Solution
# Splitting the dataset
X = spam.iloc[:, 0:56].values
y = spam.iloc[:, 57].values

In [216]:
# Importing train_test_split
from sklearn.model_selection import train_test_split

# Training using 80% of the data.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state= 0, test_size= 0.2)

In [217]:
# Training our model
#
from sklearn.naive_bayes import GaussianNB 
clf = GaussianNB()  
model = clf.fit(X_train, y_train) 


In [218]:
# Making prediction on the resting data

y_pred = model.predict(X_test)

In [219]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[387 151]
 [ 28 355]]
              precision    recall  f1-score   support

           0       0.93      0.72      0.81       538
           1       0.70      0.93      0.80       383

    accuracy                           0.81       921
   macro avg       0.82      0.82      0.81       921
weighted avg       0.84      0.81      0.81       921



In [220]:
# Importing train_test_split
from sklearn.model_selection import train_test_split

# Training using 70% of the data.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state= 0, test_size= 0.3)

In [221]:
# Training the model
#
from sklearn.naive_bayes import GaussianNB 
clf = GaussianNB()  
model = clf.fit(X_train, y_train) 


In [222]:
# Making prediction on the resting data

y_pred = model.predict(X_test)

In [223]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[598 224]
 [ 37 522]]
              precision    recall  f1-score   support

           0       0.94      0.73      0.82       822
           1       0.70      0.93      0.80       559

    accuracy                           0.81      1381
   macro avg       0.82      0.83      0.81      1381
weighted avg       0.84      0.81      0.81      1381



In [224]:
# Importing train_test_split
from sklearn.model_selection import train_test_split

# Training using 60% of the data.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state= 0, test_size= 0.4)

In [225]:
# Training the model
#
from sklearn.naive_bayes import GaussianNB 
clf = GaussianNB()  
model = clf.fit(X_train, y_train) 


In [226]:
# Making prediction on the resting data

y_pred = model.predict(X_test)

In [227]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[817 280]
 [ 45 699]]
              precision    recall  f1-score   support

           0       0.95      0.74      0.83      1097
           1       0.71      0.94      0.81       744

    accuracy                           0.82      1841
   macro avg       0.83      0.84      0.82      1841
weighted avg       0.85      0.82      0.82      1841




### Normalization

In [236]:
# Importing train_test_split
from sklearn.model_selection import train_test_split

# Training using 60% of the data.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state= 0, test_size= 0.4)

In [245]:
from sklearn.preprocessing import Normalizer
# Create normalizer
normalizer = Normalizer(norm='l1')

# Transform feature matrix
X_train = normalizer.transform(X_train)

In [246]:
# Training the model
#
from sklearn.naive_bayes import GaussianNB 
clf = GaussianNB()  
model = clf.fit(X_train, y_train) 


In [247]:
# Making prediction on the resting data

y_pred = model.predict(X_test)

In [248]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[1074   23]
 [ 487  257]]
              precision    recall  f1-score   support

           0       0.69      0.98      0.81      1097
           1       0.92      0.35      0.50       744

    accuracy                           0.72      1841
   macro avg       0.80      0.66      0.66      1841
weighted avg       0.78      0.72      0.68      1841



## 6. Follow up questions

### a). Did we have the right data?

The data available was sufficient to meet the requirements of the question

### b). Do we need other data to answer our question?

More features should be considered to ensure the accuracy of the model. 

### c). Did we have the right question?

We did have the right questions.